export const INIT_STAFF = [
  {id:1, name:"Michael Connolly",     init:"MC",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:2, name:"Aled Donaldson",       init:"AD",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:3, name:"John Allison",         init:"JA",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:4, name:"Sarah Johnson",        init:"SJ",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:5, name:"Anthony McLaughlin",   init:"AM",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:6, name:"Eleanor Burke",        init:"EB",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:7, name:"Sam Copson",           init:"SC",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:8, name:"Matthew Bankhead",     init:"MB",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:9, name:"Mark Winstanley",      init:"MW",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:10,name:"Lauren Bose",          init:"LB",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:11,name:"Cal Doherty",          init:"CD",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:12,name:"Celestine Weegenaar",  init:"CW",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:13,name:"Maud Mccutcheon",      init:"MM",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:14,name:"Jodie Sage",           init:"JS",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:15,name:"Mhairi De Saint Croix",init:"MDS", grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:16,name:"Hayley Fairbairn",     init:"HF",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:17,name:"Vay Deshpande",        init:"VD",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:18,name:"Sarah Ackroyd",        init:"SA",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:19,name:"Michael Cole",         init:"MCOL",grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:20,name:"Steven Arena",         init:"SAr", grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:21,name:"Andy Witt",            init:"AW",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:22,name:"Karl Smith",           init:"KS",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:23,name:"Nat Nauman",           init:"NN",  grade:"ST4+",hrs:45.25,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:24,name:"Nat Wright",           init:"NW",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:25,name:"Tom Field",            init:"TF",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:26,name:"Jaz Matthews",         init:"JM",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:27,name:"Steph Gooch",          init:"SG",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:28,name:"Emma Worgan",          init:"EW",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:29,name:"Mike Gammon",          init:"MG",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:30,name:"Harriet Jones",        init:"HJ",  grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:31,name:"Jack Sadler",          init:"JS2", grade:"ST3", hrs:41.75,pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:32,name:"Nikki Mavel",          init:"NM",  grade:"ACP", hrs:37.5, pw:"rota2026",role:"staff",active:true,slDays:30,militaryDays:0,nightBlockPref:"any"},
  {id:99,name:"Rota Admin",           init:"ADM", grade:"Admin",hrs:0,   pw:"admin2026",role:"admin",active:true,slDays:0,militaryDays:0,nightBlockPref:"any",isOwner:true},
];

// FTE reference targets per grade (admin can edit in Rota Config view)
export const INIT_WTE_CONFIG = {
  "ST4+":     { hoursPerWeek:45.25, hoursPerQuarter:419.85,  nights:13, weekends:6, earlies:20, mids:16, lates:20 },
  "ST3":      { hoursPerWeek:41.75, hoursPerQuarter:418.55,  nights:10, weekends:5, earlies:18, mids:14, lates:18 },
  "ACP":      { hoursPerWeek:37.5,  hoursPerQuarter:410.625, nights:8,  weekends:4, earlies:15, mids:12, lates:15 },
  "tACP":     { hoursPerWeek:37.5,  hoursPerQuarter:410.625, nights:6,  weekends:4, earlies:15, mids:12, lates:15 },
  "Military": { hoursPerWeek:27.05, hoursPerQuarter:351.6,   nights:6,  weekends:3, earlies:12, mids:9,  lates:12 },
};
